# --- Project ---
sonar.projectKey=MartaCorVa_orquestra-frontend
sonar.organization=martacorva
sonar.projectName=Orquestra Frontend
sonar.projectVersion=1.0

# --- Source code ---
sonar.sources=src
sonar.sourceEncoding=UTF-8

# --- Tests ---
sonar.tests=src/tests
sonar.test.inclusions=src/tests/**/*.test.ts

# --- Coverage ---
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# --- Exclusions ---
sonar.exclusions=\
  node_modules/**,\
  dist/**,\
  coverage/**,\
  src/tests/**,\
  src/**/*.d.ts

# --- Coverage exclusions ---
sonar.coverage.exclusions=\
  src/main.ts,\
  src/router/**,\
  src/tests/**,\
  src/**/*.d.ts